server:
  port: 8003
spring:
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大值总上传的数据大小 ：默认10M
      max-request-size: 1024MB
aliyun:
  vod:
    file:
      keyid: LTAI4GFBgPprPqBTC7gc5NTE
      keysecret: yNrZsSpHNqgw5Qa7iiW1uAa6HGy5iH