server:
  port: 8004

spring:
  application:
    name: service-cms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/college?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 192.168.56.94
    port: 6379
    database: 0
    timeout: 1800000

    lettuce:
      pool:
        max-active: 20
        pool:
          max-wait: -1
  #最大阻塞等待时间(负数表示没限制)
          max-idle: 5
          min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:com/xonlab/educms/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl