server:
  port: 8005

spring:
  application:
    name: service-msm

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/college?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.56.74
    port: 6379
    database: 0
    timeout: 1800000

    lettuce:
      pool:
        max-active: 20
        pool:
          max-wait: -1
          #最大阻塞等待时间(负数表示没限制)
          max-idle: 5
          min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:com/xonlab/msmservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl